{esp/wso/in/wso0003.i}

PROCEDURE pi-evento:

    DEFINE INPUT        PARAMETER c-evento AS CHAR NO-UNDO.
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttPessoaFisica.
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttPessoaJuridica.    
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttTelefone.          
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttEmail.             
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttEndereco.         
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttDocumento.         
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttPedido.           
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttCondicaoPagamento. 
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttItem.             
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR tt-emitente.         
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR tt-ped-venda.        
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR tt-ped-item.
    DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttErro.
    
    RETURN "OK".

END.

RETURN "OK".


