{esp/esb/esesb000.i}

DEFINE TEMP-TABLE msg0138 NO-UNDO XML-NODE-NAME 'MSG0138'
   FIELD idm AS INT XML-NODE-TYPE 'HIDDEN'
   FIELD Conta AS CHAR
   FIELD CondicaoPagamento AS INT.

DEFINE TEMP-TABLE ProdutosItens NO-UNDO XML-NODE-NAME 'ProdutosItens'
   FIELD idm AS INT XML-NODE-TYPE 'HIDDEN'.

DEFINE TEMP-TABLE ProdutoItem NO-UNDO XML-NODE-NAME 'ProdutoItem'
   FIELD idm AS INT XML-NODE-TYPE 'HIDDEN'
   FIELD CodigoProduto AS CHAR
   FIELD PrecoUnitario AS DEC
   FIELD Estabelecimento AS CHAR.

DEFINE TEMP-TABLE msg0138r NO-UNDO XML-NODE-NAME 'MSG0138R1'
   FIELD idm AS INT XML-NODE-TYPE 'HIDDEN'.

DEFINE TEMP-TABLE ProdutosItensR NO-UNDO XML-NODE-NAME 'ProdutosItens'
   FIELD idm AS INT XML-NODE-TYPE 'HIDDEN'.

DEFINE TEMP-TABLE ProdutoItemR NO-UNDO XML-NODE-NAME 'ProdutoItem'
   FIELD idm AS INT XML-NODE-TYPE 'HIDDEN'
   FIELD CodigoProduto AS CHAR
   FIELD PrecoLiquido  AS DEC
   FIELD AliquotaICMS  AS DEC FORMAT ">>9.99".
