{esp/esb/esesb000.i}

DEFINE TEMP-TABLE msg0161 NO-UNDO XML-NODE-NAME 'MSG0161'
   FIELD idm AS INT XML-NODE-TYPE 'HIDDEN'
   FIELD CodigoRepresentante AS INTEGER.

DEFINE TEMP-TABLE msg0161r NO-UNDO XML-NODE-NAME 'MSG0161R1'
   FIELD idm AS INT XML-NODE-TYPE 'HIDDEN'
   FIELD RepresentanteValido              AS INT.

DEFINE TEMP-TABLE tt-erro           NO-UNDO
    FIELD mensagem AS CHARACTER FORMAT "x(250)".
