DEFINE TEMP-TABLE cabecalho NO-UNDO XML-NODE-NAME 'CABECALHO'
   FIELD IdentidadeEmissor AS CHARACTER
   FIELD NumeroOperacao    AS CHARACTER
   FIELD CodigoMensagem    AS CHARACTER.

DEFINE TEMP-TABLE conteudo NO-UNDO XML-NODE-NAME 'CONTEUDO'
    FIELD idm AS INT XML-NODE-TYPE 'hidden'.

DEFINE TEMP-TABLE msg0059 NO-UNDO XML-NODE-NAME 'MSG0059'
   FIELD idm                 AS INT XML-NODE-TYPE 'hidden'
   FIELD CodigoContato       AS CHARACTER 
   FIELD CodigoCliente       AS INTEGER
   FIELD CodigoRepresentante AS INTEGER.

DEFINE TEMP-TABLE msg0059r NO-UNDO XML-NODE-NAME 'MSG0059R1'
   FIELD idm AS INT XML-NODE-TYPE 'hidden'.

DEFINE TEMP-TABLE resultado NO-UNDO XML-NODE-NAME 'Resultado'
   FIELD idm        AS INT XML-NODE-TYPE 'hidden'
   FIELD Sucesso    AS LOGICAL
   FIELD CodigoErro AS INTEGER
   FIELD Mensagem   AS CHARACTER FORMAT "x(100)".

DEFINE TEMP-TABLE cabecalhor NO-UNDO XML-NODE-NAME 'CABECALHO'
   FIELD IdentidadeEmissor AS CHARACTER
   FIELD NumeroOperacao    AS CHARACTER
   FIELD CodigoMensagem    AS CHARACTER.

DEFINE TEMP-TABLE conteudor NO-UNDO XML-NODE-NAME 'CONTEUDO'
   FIELD idm AS INT XML-NODE-TYPE 'hidden'.


