DEFINE VARIABLE cXml AS CHARACTER NO-UNDO.

{esp/mssp/esmssp012.i}

/* ASSIGN cXML = "<produto><it-codigo>1990025</it-codigo><un>UN</un><un-neg><![CDATA[ADMINISTRATIVO]]></un-neg><desc-item><![CDATA[Caf‚ Tradicional 500 GRS]]></desc-item><desc-inter><![CDATA[Caf‚ Tradicional  500 GRS]]></desc-inter><cod-estabel>107</cod-estabel><fm-codigo>19900007</fm-codigo><narrativa><![CDATA[CAF TORRADO, NÇO DESCAFEINADO DESTINADO AO CONSUMO HUMANO DIRETO/#MANAUS#]]></narrativa><responsavel>Adriana Flores Dalri</responsavel><peso-liquido>000.10000</peso-liquido><peso-bruto>000.10000</peso-bruto><comprim>00000.00000</comprim><largura>00000.00000</largura><altura>00000.00000</altura><ind-serv-mat>2</ind-serv-mat><tipo-contr>2</tipo-contr><ge-codigo>30</ge-codigo><contr-qualid>True</contr-qualid><fraciona>True</fraciona><perc-nqa>0.000</perc-nqa><class-fiscal>09012100</class-fiscal><destaq-ncm>002</destaq-ncm><cest></cest><perc-gatt>00.00</perc-gatt><ex-tarifario>NA</ex-tarifario><nve>NA</nve><seq-suframa></seq-suframa><versao>4</versao><data-versao>2016-03-07</data-versao><cod-acond>290</cod-acond><des-acond><![CDATA[290 - NAO SE APLICA]]></des-acond><cod-amost>10</cod-amost><des-amost>Inspe‡Æo com Base na NBR5426</des-amost><inf-adic><![CDATA[]]></inf-adic><fm-cod-com>99999990</fm-cod-com><cd-folh-item>1</cd-folh-item><criticidade>1</criticidade><ind-tipo-movto></ind-tipo-movto><reporte-ggf></reporte-ggf><cd-planejado></cd-planejado><aliquota-ii>010.000</aliquota-ii><aliquota-ipi>000.000</aliquota-ipi><aliquota-pis>001.650</aliquota-pis><aliquota-cofins>007.600</aliquota-cofins><log-necessita-li>True</log-necessita-li><log-antidumping>False</log-antidumping><obs-antidumping><![CDATA[]]></obs-antidumping></produto>". */
/* ASSIGN cXML = "<produto><it-codigo>1990084</it-codigo><un>PC</un><un-neg><![CDATA[ICORP]]></un-neg><desc-item><![CDATA[Caf‚ 200g]]></desc-item><desc-inter><![CDATA[teste]]></desc-inter><cod-estabel>101</cod-estabel><fm-codigo>19900000</fm-codigo><narrativa><![CDATA[teste#MANAUS#]]></narrativa><responsavel>Adriana Flores Dalri</responsavel><peso-liquido>000.02121</peso-liquido><peso-bruto>000.21212</peso-bruto><comprim>00000.00000</comprim><largura>00000.00000</largura><altura>00000.00000</altura><ind-serv-mat>2</ind-serv-mat><tipo-contr>2</tipo-contr><ge-codigo>30</ge-codigo><contr-qualid>True</contr-qualid><fraciona>True</fraciona><perc-nqa>0.400</perc-nqa><class-fiscal>09012100</class-fiscal><destaq-ncm>002</destaq-ncm><cest>2804300</cest><perc-gatt>00.00</perc-gatt><ex-tarifario>NA</ex-tarifario><nve>na</nve><seq-suframa></seq-suframa><versao>0</versao><data-versao>2016-03-07</data-versao><cod-acond>290</cod-acond><des-acond><![CDATA[290 - NAO SE APLICA]]></des-acond><cod-amost>10</cod-amost><des-amost>Inspe‡Æo com Base na NBR5426</des-amost><inf-adic><![CDATA[]]></inf-adic><fm-cod-com>13065010</fm-cod-com><cd-folh-item>1</cd-folh-item><criticidade>3</criticidade><ind-tipo-movto></ind-tipo-movto><reporte-ggf></reporte-ggf><cd-planejado></cd-planejado><aliquota-ii>010.000</aliquota-ii><aliquota-ipi>000.000</aliquota-ipi><aliquota-pis>001.650</aliquota-pis><aliquota-cofins>007.600</aliquota-cofins><log-necessita-li>True</log-necessita-li><log-antidumping>False</log-antidumping><obs-antidumping><![CDATA[]]></obs-antidumping></produto>". */
ASSIGN cXML = "<produto><it-codigo>1990086</it-codigo><un>PC</un><un-neg><![CDATA[ICORP]]></un-neg><desc-item><![CDATA[Caf‚ 200g]]></desc-item><desc-inter><![CDATA[teste]]></desc-inter><cod-estabel>101</cod-estabel><fm-codigo>19900000</fm-codigo><narrativa><![CDATA[teste#MANAUS#]]></narrativa><responsavel>Adriana Flores Dalri</responsavel><peso-liquido>000.02121</peso-liquido><peso-bruto>000.21212</peso-bruto><comprim>00000.00000</comprim><largura>00000.00000</largura><altura>00000.00000</altura><ind-serv-mat>2</ind-serv-mat><tipo-contr>2</tipo-contr><ge-codigo>30</ge-codigo><contr-qualid>True</contr-qualid><fraciona>True</fraciona><perc-nqa>0.400</perc-nqa><class-fiscal>09012100</class-fiscal><destaq-ncm>002</destaq-ncm><cest>2804300</cest><perc-gatt>00.00</perc-gatt><ex-tarifario>NA</ex-tarifario><nve>na</nve><seq-suframa></seq-suframa><versao>0</versao><data-versao>2016-03-07</data-versao><cod-acond>290</cod-acond><des-acond><![CDATA[290 - NAO SE APLICA]]></des-acond><cod-amost>10</cod-amost><des-amost>Inspe‡Æo com Base na NBR5426</des-amost><inf-adic><![CDATA[]]></inf-adic><fm-cod-com>13065010</fm-cod-com><cd-folh-item>1</cd-folh-item><criticidade>3</criticidade><ind-tipo-movto></ind-tipo-movto><reporte-ggf></reporte-ggf><cd-planejado></cd-planejado><aliquota-ii>010.000</aliquota-ii><aliquota-ipi>000.000</aliquota-ipi><aliquota-pis>001.650</aliquota-pis><aliquota-cofins>007.600</aliquota-cofins><log-necessita-li>True</log-necessita-li><log-antidumping>False</log-antidumping><obs-antidumping><![CDATA[]]></obs-antidumping></produto>".
ASSIGN
SESSION:DEBUG-ALERT = YES
LOG-MANAGER:LOGFILE-NAME = STRING(SESSION:TEMP-DIRECTORY + 'clientlog.txt')
LOG-MANAGER:LOGGING-LEVEL = 4
LOG-MANAGER:LOG-ENTRY-TYPES = "4GLMessages,4GLTrace,FileID".
LOG-MANAGER:CLEAR-LOG.
LOG-MANAGER:WRITE-MESSAGE("Agora t  contigo meu querido!" ).    
RUN esp/mssp/esmssp012.p (INPUT 2,
                          INPUT cXml,
                          INPUT  TABLE tt-item-fabric,
                          OUTPUT TABLE tt-mensagem).

FOR EACH tt-mensagem:
    DISP tt-mensagem.mensagem FORMAT "X(60)".
END.
