define temp-table tt-param no-undo
   field usuario  as character
   field senha    as character.

define temp-table ttCarteiraVendasResumo no-undo
   field CD_Estabelecimento              like ped-venda.cod-estabel
   field CD_Emitente                     like ped-venda.cod-emitente
   field CD_Grupo_Cliente                like emitente.cod-gr-cli
   field CD_Pedido_Cliente               like ped-venda.nr-pedcli
   field CD_Sequencia                    like ped-item.nr-sequencia
   field CD_Item                         like ped-item.it-codigo
   field CD_Unidade_Negocio              like unid-neg-ped.cod_unid_negoc
   field CD_Representante                like repres.cod-rep
   field CD_Pais                         like ped-venda.pais
   field CD_Estado                       like ped-venda.estado
   field CD_Cidade                       like ped-venda.cidade
   field TX_Emitente_Nome_Abreviado      like emitente.nome-abrev
   field TX_Emitente_Nome_Abrev_Matriz   like emitente.nome-abrev
   field TX_Representante_Nome_Abreviado like repres.nome-abrev
   field TX_Unidade_Negocio              like unid_negoc.des_unid_negoc
   field TX_Segmento                     like fam-com-item.descricao
   field TX_Familia                      like fam-com-item.descricao
   field TX_Subfamilia                   like fam-com-item.descricao
   field TX_Origem                       like fam-com-item.descricao
   field TX_Item                         like item.desc-item
   field DT_Carteira                     as date
   field NM_Qtde_Saldo                   as decimal
   field NM_Vl_Unitario                  as decimal
   field NM_Vl_Liquido                   as decimal
   field NM_Vl_Total                     as decimal
   index idx_pri is primary unique CD_Estabelecimento CD_Emitente CD_Pedido_Cliente CD_Sequencia CD_Item CD_Unidade_Negocio.
