define temp-table ttProduto no-undo
   field LojaCodigo                       as character
   field PortifolioCodigo                 as character
   field ProdutoCodigo                    as character
   field ProdutoCodigoPai                 as character
   field ProdutoCodigoInterno             as character
   field ProdutoValorCaracteristicaCodigo as character
   field FabricanteCodigo                 as character
   field ParceiroCodigo                   as character
   field ServicoCodigo                    as character
   field PrazoEntregaCodigo               as character
   field EnquadramentoCodigoInterno       as character
   field Nome                             as character
   field Titulo                           as character
   field Subtitulo                        as character
   field Descricao                        as character
   field Caracteristica                   as character
   field Texto1                           as character
   field Texto2                           as character
   field Texto3                           as character
   field Texto4                           as character
   field Texto5                           as character
   field Texto6                           as character
   field Texto7                           as character
   field Texto8                           as character
   field Texto9                           as character
   field Texto10                          as character
   field Numero1                          as character
   field Numero2                          as character
   field Numero3                          as character
   field Numero4                          as character
   field Numero5                          as character
   field Numero6                          as character
   field Numero7                          as character
   field Numero8                          as character
   field Numero9                          as character
   field Numero10                         as character
   field Estrela                          as character
   field Modelo                           as character
   field Peso                             as character
   field Altura                           as character
   field Largura                          as character
   field Profundidade                     as character
   field PesoEmbalagem                    as character
   field AlturaEmbalagem                  as character
   field LarguraEmbalagem                 as character
   field ProfundidadeEmbalagem            as character
   field PrecoCheio                       as character
   field PrecoPor                         as character
   field Voltagem                         as character
   field Entrega                          as character
   field QuantidadeMaximaPorVenda         as character
   field ProdutoStatus                    as character
   field StatusIntegracao                 as character
   field Tipo                             as character
   field Presente                         as character
   field PersonalizacaoExtra              as character
   field PersonalizacaoLabel              as character.

